### ISSUE TITLE
Display vs Values in data

### ISSUE THREAD

**Issue by macscripter** [Diaver/material-datatable#1]
Hi,
Let's suppose that I only have a column 'Employees' and  want to pass data to the table,  for example [{id:1, name:'Alex'}, {id:2, name: 'Max'}....].

Is it possible to receive data from my server as list of ids and display it by description?

Thanks

**Comment by Diaver** [comment]
Hi!

Yep, but I need make final data objects array by yourself and pass it to component according to requirements.
