### ISSUE TITLE
Text color of theme is not applied in menu

### ISSUE THREAD

**Issue by matsumotohi** [Diaver/material-datatable#11]
## Expected Behavior

When changing the text color in the theme, I also want the text color of the menu to change

## Current Behavior

Text color is fixed

## Steps to Reproduce (for bugs)

https://codesandbox.io/s/immutable-sun-5vkfj
1. Push "View Columns" button or "Filter Table" button

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.1.3     |
| Material-datatable  |    0.3.8     |
| React        |     16.8.4    |
| browser      |     Chrome    |
| etc          |         |

**Comment by Diaver** [comment]
@enshudara Fixed in 0.3.9 (2019-06-29) https://codesandbox.io/s/fervent-http-q2kds

**Comment by matsumotohi** [comment]
It's working as expected. Thank you.
