### ISSUE TITLE
column field inside object

### ISSUE THREAD

**Issue by xStorm11** [Diaver/material-datatable#13]
Hello, i receive the data inside an array of objects from my api and in some cases i need to fill my column name with a field from an object inside another object, example:
data[{a : 'abc', animals : {name: 'dog'}}]. Im using a customBodyRender to get that data.animals.name but i need to export the data from that column to a csv file, and it's not working using customBodyRender.

## Expected Behavior
I expect to have access to that data.animals.name on my CSV file. It can be fixed by having access inside the object (ex: 'field :  'animals.name') or allow the CSV file to access the customBodyRender values.

## Current Behavior
I need to use a "fake" field and use customBodyRender to do value.animals.name

## Steps to Reproduce (for bugs)
      {
        name: "Animals",
        field: "fake",
        options: {
          customBodyRender: (value, tableMeta, updateValue) => {
            return value.animals.name
          },
        },
      }

| Tech         | Version |
|--------------|---------|
| Material-datatable  |    0.3.9     |
| React        |   16.8.6      |
| browser      |    Chrome, Firefox     |

**Comment by Diaver** [comment]
@xStorm11 :

I double checked and it is working as expected.
![image](https://user-images.githubusercontent.com/644716/69892181-cf619d80-12d0-11ea-86a8-be5550073946.png)

![image](https://user-images.githubusercontent.com/644716/69892201-0e8fee80-12d1-11ea-8e15-c2b723fe4f22.png)

**Comment by xStorm11** [comment]
First of all, thanks for answering.
Yes, you're right. I found out that my issue is in handleCSVdownload().
I recently made the migration to this datatable version (0.3.9), i was using an older version (i don't remember the version) but i needed to use handleCSVdownload from the older version because that fixes the issue about fields appearing with [Object object].
But now i have 2 issues with this situation:
- If i use the handleCSVdownload from 0.3.9 i have the issue about field being [Object object], like you have in the screenshots that you put.
-If i use the older code i can't reach values inside an object of another object. (example: value.subFieldData.value)

I'm trying to get a viable solution for both problems but i'm not having success, if you could help somehow would be really nice.
I will leave here both codes:

### Old version:

```
handleCSVDownload = () => {
        const { data, columns, options } = this.props;
        const newColumns = [];
        const fields = [];
        const indexes = [];
        let newData = [];

        columns.forEach(function (val, index) {
            if (val.display === 'true') {
                newColumns.push(val);
                fields.push(val.field);
                indexes.push(index);
            }
        });

        const CSVHead =
            newColumns
                .reduce((accumulator, column) => {
                    return column.download ? `${accumulator}"${column.name}"${options.downloadOptions.separator}` : accumulator;
                }, "")
                .slice(0, -1) + "\r\n";

        const finalData = []
        data.forEach(val => {
            let string = ''
            let currentRow = []
            fields.forEach(field => {
                string = val.dataObject[field]
                currentRow.push(string)
            })
            finalData.push(currentRow)
        })

        const CSVBody = finalData
            .reduce(
                (accumulator, row) =>
                    accumulator +
                    '"' +
                    row.join('"' + options.downloadOptions.separator + '"') +
                    '"\r\n',
                [],
            )
            .trim();

```
        /* taken from react-csv */
        const csv = `${CSVHead}${CSVBody}`;
        const blob = new Blob([csv], {type: "text/csv"});
        const dataURI = `data:text/csv;charset=utf-8,${csv}`;

        const URL = window.URL || window.webkitURL;
        const downloadURI = typeof URL.createObjectURL === "undefined" ? dataURI : URL.createObjectURL(blob);

        let link = document.createElement("a");
        link.setAttribute("href", downloadURI);
        link.setAttribute("download", options.downloadOptions.filename);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

### Version 0.3.9:

```
handleCSVDownload = () => {
        const {data, columns, options} = this.props;

        const CSVHead =
            columns
                .reduce((accumulator, column) => {
                    return column.download ? `${accumulator}"${column.name}"${options.downloadOptions.separator}` : accumulator;
                }, "")
                .slice(0, -1) + "\r\n";

        const CSVBody = data
            .reduce(
                (accumulator, row) =>
                    accumulator +
                    '"' +
                    row.data
                        .filter((field, index) => columns[index].download)
                        .join('"' + options.downloadOptions.separator + '"') +
                    '"\r\n',
                [],
            )
            .trim();

        /* taken from react-csv */
        const csv = `${CSVHead}${CSVBody}`;
        const blob = new Blob([csv], {type: "text/csv"});
        const dataURI = `data:text/csv;charset=utf-8,${csv}`;

        const URL = window.URL || window.webkitURL;
        const downloadURI = typeof URL.createObjectURL === "undefined" ? dataURI : URL.createObjectURL(blob);

        let link = document.createElement("a");
        link.setAttribute("href", downloadURI);
        link.setAttribute("download", options.downloadOptions.filename);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };
```

**Comment by Diaver** [comment]
You do see [Object object] output in CSV because if you wanna return any string you need return string like here:
![image](https://user-images.githubusercontent.com/644716/70075433-d0454880-15ca-11ea-9e20-00eeab59ecb5.png)
But also you can return some object like Button:
![image](https://user-images.githubusercontent.com/644716/70075492-ec48ea00-15ca-11ea-994a-643dfdcd8020.png)

Just in this ^^ case you will see  [Object object]  output in CSV.
If you need remove this column from CSV, you can set flag "download: false" like here:
![image](https://user-images.githubusercontent.com/644716/70075621-27e3b400-15cb-11ea-9915-718c0b657200.png)

About difference in the code versions - I didn't modify this file too much and don't know what it is.

**Comment by xStorm11** [comment]
I think you don't get my point here.
In this screenshot that you put:
![image](https://user-images.githubusercontent.com/28924768/70077700-3b0d7880-15f9-11ea-8fcf-da142a7b23cf.png)

I'm trying to have access to my string inside my object like the next example and as you know this will appear [Object object] in csv file.
![image](https://user-images.githubusercontent.com/28924768/70077953-ba02b100-15f9-11ea-856d-a583061743a4.png)

This issue about [Object object] is not only for objects inside objects, it's for every customBodyRender that i'm trying to put a Link, a Button, etc...

**Comment by Diaver** [comment]
This will not work, because CSV don't anything about React and **Link.toString()** return you [Object]

**Comment by xStorm11** [comment]
The function is not ready to extract the string from the object?

**Comment by Diaver** [comment]
This function as you can see, just return some data, if you need return string, just return string.
