### ISSUE TITLE
Focus on rows

### ISSUE THREAD

**Issue by strowk** [Diaver/material-datatable#14]
## Expected Behavior
We pass focus field name in options like that `focusField: 'focus'`. When material-datatable renders it should 
1) highlight focused row same way selection is highlighting them (change background color), focused row is a row where `Boolean(row[focusField])` check is passing
2) if page was not set in options, scroll to the page, where first focused item is displayed

## Current Behavior
To implement the same have to firstly sort data the same way it would be sorted in material-datatable, split in pages and find page with first focused item to set in options. Also have to implement customBodyRender for all columns and style the background.

That's a lot of work and in case of many rows - additional load on a hardware with the second sorting.

**Comment by Diaver** [comment]
If you need it, please make a PR.
