### ISSUE TITLE
Provided options.page of x is greater than the total available page length of `1`

### ISSUE THREAD

**Issue by VassilisPallas** [Diaver/material-datatable#15]
## Expected Behavior
Page should be set to 0, when a filter is applied.

## Current Behavior
Stays on the same page and throws the below error
```
Error: Provided options.page of `3` is greater than the total available page length of `1`
```

## Steps to Reproduce (for bugs)
1. Change page
2. Select a filter that returns a number of data less than the actual results

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.7.0    |
| Material-datatable  |   0.4.0    |
| React        |   16.9.0    |
| browser      |    Chrome 79.0.3945.88 (macOS)     |

**Comment by Diaver** [comment]
Done, please update to 0.4.1
Thank you!
