### ISSUE TITLE
Can I customize datatable layout

### ISSUE THREAD

**Issue by tomohisaota** [Diaver/material-datatable#2]
Can I customize datatable layout?
I want to move pagination controller to top instead of bottom. 

If I can use DOM positioning, it will be the best.
https://datatables.net/examples/basic_init/dom.html

## Your Environment
| Tech         | Version |
|--------------|---------|
| Material-UI  |      3.5.1   |
| Material-datatable  |     0.2.1    |
| React        |      16.6.3   |
| browser      |   Safari/Chrome/Firefox/IE/Edge      |
| etc          |         |

**Comment by Diaver** [comment]
At current moment no.
Any Ideas how it should be implemented?
To be honest, I do not see to much ways how to do it.
