### ISSUE TITLE
MaterialDatatableBodyCell does not exist in type 'Overrides'

### ISSUE THREAD

**Issue by reenrik** [Diaver/material-datatable#4]
I'm trying customize cell behavior as specified in the documentation using createMuiTheme and encounter this error when using MaterialDatatableBodyCell:

Cannot find name 'MaterialDatatableBodyCell'.ts(2304)
Argument of type '{ overrides: { MuiTableCell: { root: { backgroundColor: string; paddingLeft: string; }; }; MaterialDatatableBodyCell: any; }; }' is not assignable to parameter of type 'ThemeOptions'.
  Types of property 'overrides' are incompatible.
    Type '{ MuiTableCell: { root: { backgroundColor: string; paddingLeft: string; }; }; MaterialDatatableBodyCell: any; }' is not assignable to type 'Overrides'.
      Object literal may only specify known properties, and 'MaterialDatatableBodyCell' does not exist in type 'Overrides'.ts(2345)

## Expected Behavior
Be able to override the theme as the documentation specifies.

## Current Behavior
I can customize the standard MuiTableCell field from @material-ui/core/styles, but the custom style that is rendered overrides it.

The reason I'm even looking is because when the table checkboxes are turned off, the left padding provided by MaterialDatatableBodyCell is too narrow, set to "padding: 4px 8px 4px 8px;" instead of "padding: 4px 8px 4px 24px;"

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.8.3     |
| React        |    6.4.1     |
| browser      |  Chrome       |

**Comment by Diaver** [comment]
@reenrik Something strange. Looks like error is in your app and related to TS compilation, there is no such 'MaterialDatatableBodyCell'.ts file.
Can you please share your broken peace of code via https://codesandbox.io

**Comment by reenrik** [comment]
Are you saying there SHOULD be a 'MaterialDatatableBodyCell'.ts after compilation? There is definitely a rendered class by that name in my app output in the browser, it just doesn't recognize it as a value for createMuiTheme like the documentation suggests...

I'll spend some time putting it together in codesandbox.io tomorrow, my battery is dying. :D

**Comment by Diaver** [comment]
Errors with TS files related to your own app. This package do nothing with TS except definition. Please check your app correctness more carefully.
