### ISSUE TITLE
render or mount only customBodyRender when row is visible

### ISSUE THREAD

**Issue by svensq** [Diaver/material-datatable#5]
Is it possible to use the CustomBodyRender option to render/mount/display only the cells in rows that are currently displayed (on current page, with search or filter etc)?

| Tech         | Version |
|--------------|---------|
| Material-UI  |   3.9.2      |
| Material-datatable  |    0.3.7     |
| React        |   16.8.2      |
| browser      |   Chrome      |

**Comment by Diaver** [comment]
Table component provides ability sort and filter records across whole dataset. To be able sort and filter table components needs to know what exact data it contains. That is why  CustomBodyRender and CustomHeaderRender, if presented, get called on initial mount for every record, visible or not.
