### ISSUE TITLE
"key" prop warning on column name containing icon

### ISSUE THREAD

**Issue by bluebeag** [Diaver/material-datatable#8]
Using an icon in the column name returns a warning.  

## Expected Behavior

No warning if using an icon for a header column name

## Current Behavior
index.js:1446 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `l`. See https://fb.me/react-warning-keys for more information.

## Steps to Reproduce (for bugs)
1. { field: '', name: [<FontAwesomeIcon icon={['fas','sort']} color="gray" fixedWidth size="lg" />], options: { customBodyRender: (value) => { return <strong><a href={`/WorkItemDetails/${value.ID}`}>...</a></strong> }, filter: false},},
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     3.9.2    |
| Material-datatable  |  0.3.8       |
| React        |     16.8.3    |
| browser      |         |
| etc          |         |

**Comment by Diaver** [comment]
@bluebeag 
1. Can you try set name with no "[]"?
2. Do you see error when column name value something like "name 1" (name: "test 1")?

**Comment by bluebeag** [comment]
@Diaver Removing the [] worked! Thank you!  This fix makes sense given the compiler thought it was a collection.

**Comment by bluebeag** [comment]
Solved per @Diaver solution
