### ISSUE TITLE
How to set Header and Footer Static and only scroll body

### ISSUE THREAD

**Issue by Pryorite** [Diaver/material-datatable#9]
When rows per page is set high like 100, I need a way to set the header and footer static so only the body scrolls.

## Expected Behavior
Setting a certain property should allow user to scroll body and leave header and footer static, or at the very least the header.

## Current Behavior
When scrolling it scrolls the whole datatable.

## Steps to Reproduce (for bugs)
This example has the header static and does not scroll.  Is there any way we can get this same functionality in the material-datatable?
https://material-ui.com/demos/tables/#virtualized-table

## Your Environment
I'm using the latest material-datatable - "material-datatable": "^0.3.8"

**Comment by Diaver** [comment]
@Pryorite let me check.

**Comment by bluebeag** [comment]
I really like this grid. Freezing the header is the only feature that my users are requesting. Thanks @Diaver for researching this question.

**Comment by Diaver** [comment]
@Pryorite @bluebeag 
I didn't find the good way to do it.
With all of that ways you need set  display:block and manually set column width like here http://jsfiddle.net/3fXjD/1305/

Do you know the better way to do it?

**Comment by Pryorite** [comment]
@Diaver - Looks like this sandbox project is doing what we are looking for. 
https://codesandbox.io/s/43ml13vq19 
I see they are using an AutoSizer, not sure if that has any header freezing attributes on it.  This sandbox is exactly the output we are looking for.  Thanks again all your help.  This grid has saved us many hours of code mashing.

**Comment by Diaver** [comment]
@Pryorite 
Provided example use "react-virtualized" components.
For me, it is seems to be very dramatic changes, I am not ready right now implement such changes, but I am going to play with it on this weekend.

**Comment by Peter-Pear** [comment]
@Diaver - Do you have any news on this feature?
